[default]
path = "content/entries/"
color = "#31AF31"

[index]
path = "content/index/"
prefix = "i."
emoji = "ğŸ—„"
color = "#F0C61F"
# emoji  = "ğŸªµ" ; bonsai.trunk
root = "bonsai" # index-specific property

[entry]
path = "content/entries/"
emoji = "ğŸ·"
color = "#31AF31"
# emoji  = "ğŸƒ"; bonsai.leaf
